apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: mssqldb
  name: mssqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mssqldb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: F:\source\repos\newbiedeveloper9\SharpDj\SharpdjServer\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/sharpdj-net: "true"
        io.kompose.service: mssqldb
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: Qwerty1!
        image: mcr.microsoft.com/mssql/server:2019-latest
        imagePullPolicy: Always
        name: mssqldb
        ports:
        - containerPort: 1433
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
