version: "3"

services:
  mssqldb:
    container_name: mssqldb
    user: root
    volumes:
      - ./volumes/database:/var/opt/mssql/data
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
    - "1433:1433"
    environment:
          SA_PASSWORD: "Qwerty1!"
          ACCEPT_EULA: "Y"
    networks:
    - sharpdj-net

  sharpdj-server:
    depends_on:
    - mssqldb
    image: sharpdj-server
    volumes:
    - ./volumes/logs:/apps/publish/logs
    ports:
    - "5666:5666"
    build:
      context: .
      dockerfile: SharpDj.Server/Dockerfile
    networks:
    - sharpdj-net

networks:
    sharpdj-net:
        driver: bridge